#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         8

bspc config active_border_color \#958abe
bspc config normal_border_color \#958abe
bspc config focused_border_color \#958abe

bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a KeePassXC state=floating desktop=^5
bspc rule -a Emacs state=tiled

/bin/bash $HOME/.config/scripts/jack.sh

picom &

killall -q keepassxc
keepassxc &
playerctld daemon &

emacsclient -e "(kill-emacs)"
emacs --daemon

left_monitor=$(xrandr --query | grep 'HDMI-A-0')
if [[ $left_monitor = *connected* ]]; then
    xrandr --output DisplayPort-1 --primary --auto --rotate normal --output HDMI-A-0 --auto --rotate normal --left-of DisplayPort-1
    bspc monitor DisplayPort-1 -d 1 2 3 4 5 
    bspc monitor HDMI-A-0 -d 6 7 8 9 10
    bspc wm -O DisplayPort-1 HDMI-A-0
    eww open emibar_external &
    feh --bg-fill $HOME/Pictures/wallp.png $HOME/Pictures/wallp2.png
else
    bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8
    feh --bg-fill $HOME/Pictures/wallp.png
fi

eww open emibar &

