#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 

bspc config border_width         8

bspc config active_border_color \#958abe
bspc config normal_border_color \#958abe
bspc config focused_border_color \#958abe

bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a KeePassXC state=floating desktop=^5
bspc rule -a Emacs state=tiled

feh --bg-scale $HOME/Pictures/wallp.png

/bin/bash $HOME/.config/scripts/jack.sh

picom &

killall -q keepassxc
keepassxc &
playerctld daemon &
eww open emibar &

emacsclient -e "(kill-emacs)"
emacs --daemon

